<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{9af64e0a-fb58-4afa-a9f3-d1fb4ab77c3d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_HEARTBEAT();
PRG_OverridePressure();
PRG_SIMULATION();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="16" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>